#ifndef BOMBERMAN_GLOBALS_H
# define BOMBERMAN_GLOBALS_H 1

/*
	int	BOMBERMAN_PLAYER_UP = 0;
	int	BOMBERMAN_PLAYER_DOWN = 1;
	int	BOMBERMAN_PLAYER_LEFT = 2;
	int	BOMBERMAN_PLAYER_RIGHT = 3;

	int BOMBERMAN_BOMB_SET = 4;
*/

#endif /* BOMBERMAN_GLOBALS_H */